var mongo = require('mongodb');
var MongoClient = require('mongodb').MongoClient;
var MongoUrl = "mongodb://localhost:27017/mydb";
var client = new MongoClient(MongoUrl);

var dbo;


client.connect(function(err){
	//open update database
	dbo = client.db("mydb");

	/*testing stuff
	addUser({
		username: "kevin",
		password: "pass",
		prefArr: ['pref1', 'pref2', 'pref3']
	});
	*/
	
	/*
	addNP("", {name: "", item: "" })
	*/
	/*
	dbo.collection("NP").insertMany(
		[{name: "TEXAS WOMENS FOUNDATION", item: "water bottle"},
		{name: "Young Women's Preparatory Network", item: "water bottle"},
		{name: "Women In Need of Generous Support", item: "clothes"},
		{name: "Womens Foodservice Forum", item: "clothes"},
		{name: "H.I.S. BRIDGEBUILDERS", item: "water bottle"},
		{name: "SKILL QUEST", item: "clothes"},
		{name: "Inclusive Communities Housing Development Corporation", item: "water bottle"},
		{name: "GREEN CAREERS DALLAS", item: "clothes"},
		{name: "H.I.S. BRIDGEBUILDERS", item: "clothes"},
		{name: "SKILL QUEST", item: "clothes"},
		{name: "Inclusive Communities Housing Development Corporation", item: "water bottle"},
		{name: "GREEN CAREERS DALLAS", item: "water bottle"}]
	);
	*/
	dbo.collection("NP").insertMany(
{ organization_id: '8162434',
		item: "water bottle",
       bridge_id: '3382100366',
       ein: '75-2048261',
       organization_name: 'TEXAS WOMENS FOUNDATION',
       also_known_as: 'Dallas Women\'s Foundation',
       mission: 'Texas Women’s Foundation (formerly Dallas Women’s Foundation) is a catalyst for positive change across the state, with a focused mission and vision to empower strong women to build a better world.',
       address_line_1: '8150 N Central Expy Ste 110',
       address_line_2: 'Campbell Centre II',
       city: 'Dallas',
       state: 'TX',
       zip: '75206',
       county: 'Dallas',
       msa: 'TX - Dallas-Fort Worth',
       lat_long: '32.8305,-96.7727',
       ntee_code: 'Z99 Unknown',
       profile_level: 'SILVER',
       public_report: 'https://www.guidestar.org/profile/75-2048261',
       subsection_code: '501(c)(3) Public Charity',
       number_of_employees: '20',
       form_type: '990',
       website_url: 'www.txwf.org',
       foundation_code: '15',
       parent_orgs: '',
       bmf_gross_receipts: '8012269',
       bmf_assets: '33740910',
       form990_total_revenue: '7641738',
       form990_total_expenses: '7990584',
       form990_total_assets: '33740910',
       contact_email: 'ksenters@dallaswomensfoundation.org',
       contact_name: 'Kristyn Senters',
       contact_phone: '(214) 525-5323',
       contact_title: 'Communications Director',
         },
     { organization_id: '7698233',
 		item: "water bottle",
      bridge_id: '4704797067',
       ein: '47-0902114',
       organization_name: 'Young Women\'s Preparatory Network',
       also_known_as: '',
       mission: 'To support single-gender, college-preparatory, public education in Texas and beyond, giving young women the academic and leadership skills to achieve success in college and in life.',
       address_line_1: '1722 Routh Street, Suite 720',
       address_line_2: '',
       city: 'Dallas',
       state: 'TX',
       zip: '75201',
       county: 'Dallas',
       msa: 'TX - Dallas-Fort Worth',
       lat_long: '32.7872,-96.7985',
       ntee_code: 'B90 Educational Services and Schools - Other',
       profile_level: 'PLATINUM',
       public_report: 'https://www.guidestar.org/profile/47-0902114',
       subsection_code: '501(c)(3) Public Charity',
       number_of_employees: '14',
       form_type: '990',
       website_url: 'www.youngwomensprep.org',
       foundation_code: '15',
       parent_orgs: '',
       bmf_gross_receipts: '2826071',
       bmf_assets: '6030997',
       form990_total_revenue: '2386502',
       form990_total_expenses: '2770254',
       form990_total_assets: '6030997',
       contact_email: 'cryan@ywprep.org',
       contact_name: 'Ms. Cindy Ryan',
       contact_phone: '(214) 824-1400',
       contact_title: 'Director of Development',
         },
     { organization_id: '8144728',
 		item: "clothes",
      bridge_id: '7343492288',
       ein: '75-0800699',
       organization_name: 'Women In Need of Generous Support',
       also_known_as: 'WiNGS',
       mission: 'Our mission at WiNGS is to empower women, fight poverty, and impact generations.     We address the most critical needs of women in Dallas County, offering programs in the areas of financial capability and work skills support, pregnancy and parenting education, and small business development.',
       address_line_1: '2603 Inwood Rd.',
       address_line_2: '',
       city: 'Dallas',
       state: 'TX',
       zip: '75235',
       county: 'Dallas',
       msa: 'TX - Dallas-Fort Worth',
       lat_long: '32.8286,-96.8427',
       ntee_code: 'P20 Human Service Organizations',
       profile_level: 'SILVER',
       public_report: 'https://www.guidestar.org/profile/75-0800699',
       subsection_code: '501(c)(3) Public Charity',
       number_of_employees: '56',
       form_type: '990',
       website_url: 'http://wingsdallas.org',
       foundation_code: '15',
       parent_orgs: '',
       bmf_gross_receipts: '4778535',
       bmf_assets: '4516655',
       form990_total_revenue: '4725791',
       form990_total_expenses: '4682777',
       form990_total_assets: '4516655',
       contact_email: 'ssmithson@WiNGSdallas.org',
       contact_name: 'Ms. Susan Smithson',
       contact_phone: '(214) 826-9922',
       contact_title: 'Chief Operations Officer',
         },
     { organization_id: '7494858',
  		item: "clothes",
      bridge_id: '2994604507',
       ein: '36-4349795',
       organization_name: 'Womens Foodservice Forum',
       also_known_as: '',
       mission: 'To Engage In Intitiatives That Support Career Development Of Women In The Foodservice And Hospitality Industries.',
       address_line_1: '6730 LYNDON B JOHNSON FWY',
       address_line_2: '',
       city: 'Dallas',
       state: 'TX',
       zip: '75240',
       county: 'Dallas',
       msa: 'TX - Dallas-Fort Worth',
       lat_long: '32.932,-96.7892',
       ntee_code: 'K34 Congregate Meals',
       profile_level: 'NONE',
       public_report: 'https://www.guidestar.org/profile/36-4349795',
       subsection_code: '501(c)(3) Public Charity',
       number_of_employees: '27',
       form_type: '990',
       website_url: 'WWW.WOMENSFOODSERVICEFORUM.COM',
       foundation_code: '15',
       parent_orgs: '',
       bmf_gross_receipts: '9692697',
       bmf_assets: '7526331',
       form990_total_revenue: '9022964',
       form990_total_expenses: '8995932',
       form990_total_assets: '7526331',
       contact_email: null,
       contact_name: null,
       contact_phone: null,
       contact_title: null,
         },
     { organization_id: '8186081',
  		item: "water bottle",
      bridge_id: '2416239076',
       ein: '75-2596111',
       organization_name: 'H.I.S. BRIDGEBUILDERS',
       also_known_as: 'BridgeBuilders',
       mission: 'BridgeBuilders is making poverty history by confronting the spiritual, cultural and material conditions that foster and sustain urban poverty. This holistic approach begins with resident missionaries bringing the Gospel of Jesus into inner-city communities that suffer from extreme spiritual, social and cultural brokenness.',
       address_line_1: 'PO Box 702545',
       address_line_2: '',
       city: 'Dallas',
       state: 'TX',
       zip: '75370',
       county: 'Dallas',
       msa: 'TX - Dallas-Fort Worth',
       lat_long: '32.9998,-96.8417',
       ntee_code: 'X20 Christian',
       profile_level: 'GOLD',
       public_report: 'https://www.guidestar.org/profile/75-2596111',
       subsection_code: '501(c)(3) Public Charity',
       number_of_employees: '0',
       form_type: '990',
       website_url: 'https://bridgebuilders.org/',
       foundation_code: '15',
       parent_orgs: '',
       bmf_gross_receipts: '746239',
       bmf_assets: '693822',
       form990_total_revenue: '746239',
       form990_total_expenses: '1128826',
       form990_total_assets: '693822',
       contact_email: 'ddearmas@bridgebuilders.org',
       contact_name: 'Mr. Delton de Armas',
       contact_phone: '(469) 621-5982',
       contact_title: 'Director of Operations',
         },
     { organization_id: '9253892',
  		item: "clothes",
       bridge_id: '7825517135',
       ein: '45-4536492',
       organization_name: 'SKILL QUEST',
       also_known_as: 'Skill QUEST',
       mission: 'THE MISSION OF SKILL QUEST IS TO LIFT WORKING ADULTS OUT OF POVERTY INTO FAMILY LIVING WAGE CAREERS THROUGH EDUCATION.',
       address_line_1: '1111 West Mockingbird Lane, Suite 570',
       address_line_2: '',
       city: 'Dallas',
       state: 'TX',
       zip: '75247',
       county: 'Dallas',
       msa: 'TX - Dallas-Fort Worth',
       lat_long: '32.8141,-96.8796',
       ntee_code: 'J22 Employment Training',
       profile_level: 'BRONZE',
       public_report: 'https://www.guidestar.org/profile/45-4536492',
       subsection_code: '501(c)(3) Public Charity',
       number_of_employees: '8',
       form_type: '990',
       website_url: 'www.skillquestntx.org',
       foundation_code: '15',
       parent_orgs: '',
       bmf_gross_receipts: '480880',
       bmf_assets: '187337',
       form990_total_revenue: '480880',
       form990_total_expenses: '574192',
       form990_total_assets: '187337',
       contact_email: 'RGrant@skillquestntx.org',
       contact_name: 'Reginald Grant',
       contact_phone: '(214) 421-3555',
       contact_title: 'Executive Director',
         },
     { organization_id: '8916558',
   		item: "water bottle",
      bridge_id: '3009931112',
       ein: '27-0814295',
       organization_name: 'Inclusive Communities Housing Development Corporation',
       also_known_as: '',
       mission: 'The Inclusive Communities Housing Development Corporation (Ichdc) Is A 501(C)(3) Organization Established By The Inclusive Communities Project (Icp). The Organization Expands Fair Housing Opportunities By Facilitating The Development Of Affordable Housing For Low Income Families In Low Poverty, Non-Minority Communities Of The Dallas Metropolitan Area.',
       address_line_1: '3301 ELM ST',
       address_line_2: '',
       city: 'Dallas',
       state: 'TX',
       zip: '75226',
       county: 'Dallas',
       msa: 'TX - Dallas-Fort Worth',
       lat_long: '32.7831,-96.7752',
       ntee_code: 'S20 Community, Neighborhood Development, Improvement',
       profile_level: 'NONE',
       public_report: 'https://www.guidestar.org/profile/27-0814295',
       subsection_code: '501(c)(3) Public Charity',
       number_of_employees: '0',
       form_type: '990',
       website_url: 'N/A',
       foundation_code: '15',
       parent_orgs: '',
       bmf_gross_receipts: '471928',
       bmf_assets: '2105290',
       form990_total_revenue: '344229',
       form990_total_expenses: '164411',
       form990_total_assets: '2443781',
       contact_email: null,
       contact_name: null,
       contact_phone: null,
       contact_title: null,
         },
     { organization_id: '9585382',
  		item: "clothes",
       bridge_id: '7860521140',
       ein: '81-4268182',
       organization_name: 'GREEN CAREERS DALLAS',
       also_known_as: 'Green Careers Dallas',
       mission: 'Disrupting poverty through green career training and community education.',
       address_line_1: '2631 LAKEFOREST CT',
       address_line_2: '',
       city: 'Dallas',
       state: 'TX',
       zip: '75214',
       county: 'Dallas',
       msa: 'TX - Dallas-Fort Worth',
       lat_long: '32.8229,-96.7484',
       ntee_code: 'J22 Employment Training',
       profile_level: 'BRONZE',
       public_report: 'https://www.guidestar.org/profile/81-4268182',
       subsection_code: '501(c)(3) Public Charity',
       number_of_employees: '',
       form_type: '',
       website_url: 'www.greencareersdallas.org',
       foundation_code: '15',
       parent_orgs: '',
       bmf_gross_receipts: '0',
       bmf_assets: '0',
       form990_total_revenue: '',
       form990_total_expenses: '',
       form990_total_assets: '',
       contact_email: 'tracy@greencareersdallas.org',
       contact_name: 'Tracy Wallace',
       contact_phone: '(214) 676- x0176',
       contact_title: 'Executive Director'},
     { organization_id: '8186081',
   		item: "clothes",
      bridge_id: '2416239076',
       ein: '75-2596111',
       organization_name: 'H.I.S. BRIDGEBUILDERS',
       also_known_as: 'BridgeBuilders',
       mission: 'BridgeBuilders is making poverty history by confronting the spiritual, cultural and material conditions that foster and sustain urban poverty. This holistic approach begins with resident missionaries bringing the Gospel of Jesus into inner-city communities that suffer from extreme spiritual, social and cultural brokenness.',
       address_line_1: 'PO Box 702545',
       address_line_2: '',
       city: 'Dallas',
       state: 'TX',
       zip: '75370',
       county: 'Dallas',
       msa: 'TX - Dallas-Fort Worth',
       lat_long: '32.9998,-96.8417',
       ntee_code: 'X20 Christian',
       profile_level: 'GOLD',
       public_report: 'https://www.guidestar.org/profile/75-2596111',
       subsection_code: '501(c)(3) Public Charity',
       number_of_employees: '0',
       form_type: '990',
       website_url: 'https://bridgebuilders.org/',
       foundation_code: '15',
       parent_orgs: '',
       bmf_gross_receipts: '746239',
       bmf_assets: '693822',
       form990_total_revenue: '746239',
       form990_total_expenses: '1128826',
       form990_total_assets: '693822',
       contact_email: 'ddearmas@bridgebuilders.org',
       contact_name: 'Mr. Delton de Armas',
       contact_phone: '(469) 621-5982',
	 contact_title: 'Director of Operations',},
     { organization_id: '9253892',
  		item: "clothes",
       bridge_id: '7825517135',
       ein: '45-4536492',
       organization_name: 'SKILL QUEST',
       also_known_as: 'Skill QUEST',
       mission: 'THE MISSION OF SKILL QUEST IS TO LIFT WORKING ADULTS OUT OF POVERTY INTO FAMILY LIVING WAGE CAREERS THROUGH EDUCATION.',
       address_line_1: '1111 West Mockingbird Lane, Suite 570',
       address_line_2: '',
       city: 'Dallas',
       state: 'TX',
       zip: '75247',
       county: 'Dallas',
       msa: 'TX - Dallas-Fort Worth',
       lat_long: '32.8141,-96.8796',
       ntee_code: 'J22 Employment Training',
       profile_level: 'BRONZE',
       public_report: 'https://www.guidestar.org/profile/45-4536492',
       subsection_code: '501(c)(3) Public Charity',
       number_of_employees: '8',
       form_type: '990',
       website_url: 'www.skillquestntx.org',
       foundation_code: '15',
       parent_orgs: '',
       bmf_gross_receipts: '480880',
       bmf_assets: '187337',
       form990_total_revenue: '480880',
       form990_total_expenses: '574192',
       form990_total_assets: '187337',
       contact_email: 'RGrant@skillquestntx.org',
       contact_name: 'Reginald Grant',
       contact_phone: '(214) 421-3555',
       contact_title: 'Executive Director',
       },
     { organization_id: '8916558',
       bridge_id: '3009931112',
  		item: "water bottle",
       ein: '27-0814295',
       organization_name: 'Inclusive Communities Housing Development Corporation',
       also_known_as: '',
       mission: 'The Inclusive Communities Housing Development Corporation (Ichdc) Is A 501(C)(3) Organization Established By The Inclusive Communities Project (Icp). The Organization Expands Fair Housing Opportunities By Facilitating The Development Of Affordable Housing For Low Income Families In Low Poverty, Non-Minority Communities Of The Dallas Metropolitan Area.',
       address_line_1: '3301 ELM ST',
       address_line_2: '',
       city: 'Dallas',
       state: 'TX',
       zip: '75226',
       county: 'Dallas',
       msa: 'TX - Dallas-Fort Worth',
       lat_long: '32.7831,-96.7752',
       ntee_code: 'S20 Community, Neighborhood Development, Improvement',
       profile_level: 'NONE',
       public_report: 'https://www.guidestar.org/profile/27-0814295',
       subsection_code: '501(c)(3) Public Charity',
       number_of_employees: '0',
       form_type: '990',
       website_url: 'N/A',
       foundation_code: '15',
       parent_orgs: '',
       bmf_gross_receipts: '471928',
       bmf_assets: '2105290',
       form990_total_revenue: '344229',
       form990_total_expenses: '164411',
       form990_total_assets: '2443781',
       contact_email: null,
       contact_name: null,
       contact_phone: null,
       contact_title: null,
       },
     { organization_id: '9585382',
  		item: "water bottle",
       bridge_id: '7860521140',
       ein: '81-4268182',
       organization_name: 'GREEN CAREERS DALLAS',
       also_known_as: 'Green Careers Dallas',
       mission: 'Disrupting poverty through green career training and community education.',
       address_line_1: '2631 LAKEFOREST CT',
       address_line_2: '',
       city: 'Dallas',
       state: 'TX',
       zip: '75214',
       county: 'Dallas',
       msa: 'TX - Dallas-Fort Worth',
       lat_long: '32.8229,-96.7484',
       ntee_code: 'J22 Employment Training',
       profile_level: 'BRONZE',
       public_report: 'https://www.guidestar.org/profile/81-4268182',
       subsection_code: '501(c)(3) Public Charity',
       number_of_employees: '',
       form_type: '',
       website_url: 'www.greencareersdallas.org',
       foundation_code: '15',
       parent_orgs: '',
       bmf_gross_receipts: '0',
       bmf_assets: '0',
       form990_total_revenue: '',
       form990_total_expenses: '',
       form990_total_assets: '',
       contact_email: 'tracy@greencareersdallas.org',
       contact_name: 'Tracy Wallace',
       contact_phone: '(214) 676- x0176',
       contact_title: 'Executive Director',
       }	
	);
	
	console.log(dbo.collection("NP").find());
});

//non profit information
 function addNP(name, table){
	//table = { itemsWanted: {food: true, water: false, papertowels: false, clothes: true} }
	dbo.collection("NP").insertOne(table, function(err, res){
		if(err) throw err;
	});
}

function getNP(item, callback, charity){
	dbo.collection("NP").find({'item': item}).toArray(function(err,docs){
		callback(docs);
	});
}

//user functions
function addUser(table, res){
	//see if the user exists
	userExists(table.username, function(temp){
		if(temp){ 
			res.json({auth: false});
			res.end();
			return; 
		};
		
		dbo.collection("Users").insertOne(table, function(err, temp){
			if(err) throw err;
			
			res.json({auth: true});
			res.end();
		});
	});
}

function updateUser(table, callback){
	dbo.collection("Users").updateOne({'username': table.username}, 
		{ $set: table },
		{upsert: true}
	);
}

function getUser(name, callback){
	dbo.collection("Users").find({'username': name}).toArray(function(err,docs){
		callback(docs[0]);
	});
}

function userExists(name, callback){
	dbo.collection("Users").find({'username': name}).toArray(function(err,docs){
		callback(docs.length > 0);
	});	
}

//transactions
function donateItem(user, name, Np){
	
}

function donateMoney(user, name, Np, amount){
	
}




function closeDB(){
	client.close(); //close out the database
}

module.exports = {
	addNP: addNP,
	addUser: addUser,
	donateItem: donateItem,
	donateMoney: donateMoney,
	getUser: getUser,
	getNP: getNP,
	userExists: userExists,
	closeDB: closeDB,
};


